name: Auto Cite
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  update_research:
    name: Auto Cite
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install packages
        run: python -m pip install --upgrade --requirement ./auto-cite/requirements.txt
      - name: Build updated citations
        run: python ./auto-cite/auto-cite.py
        timeout-minutes: 15
      - name: Commit updated citations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "_data/citations.yaml"
          commit_message: "Generate citations"
          push_options: --force
